### PR TITLE
fix: fixed issue with reset to default not working

### LINKED ISSUE #554: TableColumnAutoSizing  "Reset to Default" is not working
https://docs.webforj.com/webforj/tablecolumnautosizing?

- Click "Auto-Fit to Table Width"
- Click "Reset to Default" -> does not work

### PR DESCRIPTION
**Pull request by laurenic0l**
closes #554

### CODE REVIEW

File: src/main/java/com/webforj/samples/views/table/TableColumnAutoSizingView.java [hunk 1]
```diff
@@ -84,50 +88,23 @@ private Table<MusicRecord> createTable() {
   }
 
   private void autoSizeAllColumns() {
-    table.setColumnsToAutoSize().thenAccept(ignored -> {
-    });
+    table.setColumnsToAutoSize().thenAccept(ignored -> {});
```
Comment (hyyan) [inline src/main/java/com/webforj/samples/views/table/TableColumnAutoSizingView.java:91]: remove all `.thenAccept(ignored -> {});` please

File: src/main/java/com/webforj/samples/views/table/TableColumnAutoSizingView.java [hunk 2]
```diff
@@ -84,50 +88,23 @@ private Table<MusicRecord> createTable() {
...
-        .orElse(null);
-
-    if (titleColumn != null) {
-      table.setColumnToAutoSize(titleColumn).thenAccept(ignored -> {
-      });
-    }
+    table.setColumnToAutoSize(titleCol).thenAccept(ignored -> {});
   }
 
   private void resetToDefaults() {
```
Comment (hyyan) [inline src/main/java/com/webforj/samples/views/table/TableColumnAutoSizingView.java:102]: This repeats code from the createTable method. Refactor to remove the duplication please.

**Review by hyyan — CHANGES_REQUESTED** [review]

**Review by MatthewHawkins — APPROVED** [review]
