### PR TITLE
fix(datefield): handle invalid and cleared inputs without crashing

### LINKED ISSUE #268: Entering "0" in Departure Date field triggers 500 server error
### **Description**
In the Date Field demo on docs.webforj.com, manually typing 0 into the "Departure Date" input field results in a 500 Internal Server Error, breaking the page and preventing further interaction.

### **Steps to Reproduce**
1. Navigate to https://docs.webforj.com/webforj/datefield.
2. Locate the "Departure Date" field.
3. Click inside the field and delete the existing value.
4. Type 0 and observe the page.

**NOTE**: For Firefox, after typing 0, the user must click outside the input to get a 500 error. 

### **Expected Result**
The input should either be ignored as invalid or prompt the user with validation feedback without breaking the page.

### **Actual Result**
The application crashes and displays a 500 Internal Server Error page.

Browser: Google Chrome 135.0.7049.85 and Firefox 137.0.1
OS: Windows 11
Timestamp: April 14, 2025

https://github.com/user-attachments/assets/33b15f9a-d4b2-4cdd-b427-79dbd99933d9

### LINKED ISSUE #269: Entering a year value over 9999 in date field triggers 500 server error
### **Description**
When a user manually enters a date with a year greater than 9999 (e.g., 11/11/11111) in the Departure Date field, the application throws a 500 Internal Server Error, indicating the backend cannot handle such values.

### **Steps to Reproduce**

1. Go to https://docs.webforj.com/webforj/datefield.
2. Click into either the "Departure Date" or "Return Date" field.
3. Enter the date 11/11/11111.
4. Press Enter or click outside the field.

**NOTE:** In the video, the first screen shows Firefox, and the second screen displays Chrome. However, it did not occur on Safari. 

### **Expected Result**
The input should be rejected as invalid, with client-side validation or feedback shown to the user.

### **Actual Result**
The page crashes and displays a 500 Internal Server Error message.

https://github.com/user-attachments/assets/becfed9b-1a4d-4fb1-a911-b81c9eea4de1

### LINKED ISSUE #270: Deleting the Departure Date input causes 500 server error in Date Field
### **Description**
When a user clears the "Departure Date" field by pressing backspace or delete, the app crashes and displays a 500 Internal Server Error. This occurs without submitting or interacting with any other fields.

### **Steps to Reproduce**
1. Navigate to https://docs.webforj.com/webforj/datefield.
2. Click inside the "Departure Date" input field.
3. Press backspace or delete until the field is empty.
4. Click outside the field or press Enter.

### **Expected Result**
The field should either show a validation error for empty input or allow the user to clear the value without triggering an error.

### **Actual Result**
The page crashes and displays a 500 Internal Server Error.

Browser: Google Chrome 135.0.7049.85 and Firefox 137.0.1
OS: Windows 11
Timestamp: April 14, 2025

https://github.com/user-attachments/assets/86f7f022-09c9-450f-ae97-c322009b40c2

### LINKED ISSUE #273: 500 Server Error When Clicking "Clear" in Date Field
### **Description**
Clicking the "Clear" button in the calendar popup triggers a 500 Internal Server Error. This occurs on the "Departure Date" field and halts further interaction.

### **Steps to Reproduce**

1. Navigate to the date field demo page: https://docs.webforj.com/webforj/datefield?
2. Click into the "Departure Date" input to open the calendar widget.
3. Without selecting any new date, click the "Clear" option at the bottom of the calendar popup.

### **Expected Result**
The selected date should be cleared, and the input field should reflect a blank or null state without error.

### **Actual Result**
A 500 Internal Server Error page is triggered, and the application becomes unresponsive.

### **Environment Details**

- Browser: Chrome 135.0.7049.85, Firefox 137.0.1
- OS: Windows 11

Image

### PR DESCRIPTION
**Pull request by laurenic0l**
- Prevented 500 errors caused by clearing the date field or entering invalid formats (e.g., year > 9999 or 0)
- Ensured clearing sets value to null instead of triggering backend issues
- Improved departure/return logic to auto-adjust return date when needed

- closes #273 
- closes #270
- closes #269
- closes #268

### CODE REVIEW

**Comment by laurenic0l** [comment]
@jturfanbasis I believe this fixes the issues with the date field demo. Let me know if I missed anything

**Comment by jturfanbasis** [comment]
@laurenic0l Yes, I tested it, and it works well. Could you change the variable names to: 

Instead of "departure," use "departureField," and change "arrivalDate" to "returnDate" for better readability?

Thank you.

**Review by jturfanbasis — DISMISSED** [review]

File: src/main/java/com/webforj/samples/views/fields/datefield/DateFieldView.java [hunk 1]
```diff
@@ -17,12 +18,13 @@ public class DateFieldView extends Composite<FlexLayout> {
...
+        .setDirection(FlexDirection.ROW)
+        .setSpacing("var(--dwc-space-l)")
+        .setMargin("var(--dwc-space-m)");
 
     departure.setLabel("Departure Date:")
         .setWidth("200px")
-        .setMin(LocalDate.now())
         .addValueChangeListener(this::setMinReturn);
 
     returnField.setLabel("Return Date:")
```
Comment (bbrennanbasis) [inline src/main/java/com/webforj/samples/views/fields/datefield/DateFieldView.java:30]: @laurenic0l Could you please also add a ValueChangeListener event to returnField? The app still crashes if it the Return Date is null and the user tries to change the Departure date.

Comment (laurenic0l) [reply src/main/java/com/webforj/samples/views/fields/datefield/DateFieldView.java:31]: @bbrennanbasis thanks for catching that. I think it should be good now

**Review by hyyan — CHANGES_REQUESTED** [review]
@laurenic0l John’s code is not quite working as expected. Right now, the two date fields don’t sync properly. For example, if you change the return date, the departure date doesn’t adjust at all, which can easily lead to inconsistent input. Might be good to revisit the logic so both fields stay in sync when users change either one.

**Comment by hyyan** [comment]
@laurenic0l Your solution works, but it complicates things and interferes with the client-side validation logic. The goal is to validate the input on the server without blocking the browser from showing meaningful validation messages.

I suggest trying the following approach. It simplifies the logic and keeps validation feedback clear on the client side. Please test it against the open issues and adjust if needed:

```java
package com.webforj.samples.views.fields.datefield;

import java.time.LocalDate;

import com.webforj.component.Composite;
import com.webforj.component.field.DateField;
import com.webforj.component.layout.flexlayout.FlexDirection;
import com.webforj.component.layout.flexlayout.FlexLayout;
import com.webforj.data.event.ValueChangeEvent;
import com.webforj.router.annotation.FrameTitle;
import com.webforj.router.annotation.Route;

@Route
@FrameTitle("Date Field Demo")
public class DateFieldView extends Composite<FlexLayout> {

  private static final LocalDate TODAY = LocalDate.now();
  private static final LocalDate MAX_DATE = TODAY.plusYears(1);

  private final DateField departureField = new DateField(TODAY);
  private final DateField returnField = new DateField(TODAY);

  public DateFieldView() {
    getBoundComponent()
        .setDirection(FlexDirection.ROW)
        .setSpacing("var(--dwc-space-l)")
        .setMargin("var(--dwc-space-m)");

    departureField.setLabel("Departure Date:")
        .setWidth("200px")
        .setMin(TODAY)
        .setMax(MAX_DATE)
        .addValueChangeListener(this::syncDates);

    returnField.setLabel("Return Date:")
        .setWidth("200px")
        .setMin(TODAY)
        .setMax(MAX_DATE)
        .addValueChangeListener(this::syncDates);

    getBoundComponent().add(departureField, returnField);
  }

  private void syncDates(ValueChangeEvent<LocalDate> e) {
    LocalDate rawDep = departureField.getValue();
    LocalDate rawRet = returnField.getValue();

    LocalDate dep = clamp(rawDep);
    LocalDate ret = clamp(rawRet);

    if (dep == null || ret == null) {
      return;
    }

    if (ret.isBefore(dep)) {
      if (e.getSource() == departureField)
        returnField.setValue(dep);
      else
        departureField.setValue(ret);
    }
  }

  private LocalDate clamp(LocalDate date) {
    if (date == null)
      return null;
    return date.isBefore(TODAY) ? TODAY
        : date.isAfter(MAX_DATE) ? MAX_DATE
            : date;
  }
}
```

**Comment by laurenic0l** [comment]
@hyyan after testing your solution there are no 500 errors!
@jturfanbasis please confirm if anything was missed

**Review by jturfanbasis — APPROVED** [review]
